### ISSUE TITLE
[BUG] - The module is exporting to AC empty carts

### ISSUE THREAD

**Issue by LucaGallinari** [webgriffe/SyliusActiveCampaignPlugin#71]
**Describe the bug**
The module is exporting to Active Campaign empty carts as abandoned carts. There is no filter on the Repository's method or on the Command that filters out these type of cart.

**Comment by lruozzi9** [comment]
You are right @LucaGallinari ! Thank you.
But, how can you create empty cart? If I'm not wrong, the cart is created only when the first item is added. Is it possible that this issue is due to some "custom application logic"?
Anyway I don't see anything of wrong by adding this check!

**Comment by LucaGallinari** [comment]
You can replicate it by adding a product to the cart and removing it afterward
