### ISSUE TITLE
[BUG] - ChannelHostnameUrlGenerator fails when called in async message bus handler

### ISSUE THREAD

**Issue by maxmishyn** [webgriffe/SyliusActiveCampaignPlugin#76]
In the environment with async message bus it is not possible to send one order information to ActiveCampaign due exception in ChannelHostnameUrlGenerator. 
It fails with the following error message in the log.
`Symfony\\Component\\HttpFoundation\\Exception\\SessionNotFoundException(code: 0): There is currently no session available.?? at /home/wadwshop/sylius/vendor/symfony/http-foundation/RequestStack.php:105`

I was able to trace it till the $this->urlGenerator->generate(...) method call. But currently no idea why in this situation CompiledUrlGenerator needs session to build URL.

**To Reproduce**
1. Setup 'Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderCreate' messages to be handled by any async queue  
2. Send any order to AC with CLI `command bin/console webgriffe:active-campaign:enqueue-ecommerce-order 12345`
3. Consume message queue consumer
4. check the log. In my case it has something like this:
messenger.CRITICAL: Error thrown while handling message Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderCreate. Removing from transport after 3 retries. Error: "Handling "Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderCreate" failed: There is currently no session available.??" 

`
{"class":"Webgriffe\\SyliusActiveCampaignPlugin\\Message\\EcommerceOrder\\EcommerceOrderCreate","retryCount":3,"error":"Handling \"Webgriffe\\SyliusActiveCampaignPlugin\\Message\\EcommerceOrder\\EcommerceOrderCreate\" failed: There is currently no session available.??","exception":"[object] (Symfony\\Component\\Messenger\\Exception\\HandlerFailedException(code: 0): Handling \"Webgriffe\\SyliusActiveCampaignPlugin\\Message\\EcommerceOrder\\EcommerceOrderCreate\" failed: There is currently no session available. at /xxxxxx/sylius/vendor/symfony/doctrine-bridge/Messenger/DoctrineTransactionMiddleware.php:42)\n[previous exception] [object] (Symfony\\Component\\HttpFoundation\\Exception\\SessionNotFoundException(code: 0): There is currently no session available.?? at /xxxxxx/sylius/vendor/symfony/http-foundation/RequestStack.php:105)"} []
[2023-09-13T15:45:10.278320+00:00] messenger.INFO: Rejected message Webgriffe\SyliusActiveCampaignPlugin\Message\EcommerceOrder\EcommerceOrderCreate will be sent to the failure transport Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport. {"class":"Webgriffe\\SyliusActiveCampaignPlugin\\Message\\EcommerceOrder\\EcommerceOrderCreate","transport":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
`

**Comment by lruozzi9** [comment]
Good to hear that it works, thanks!
