### ISSUE TITLE
Use liip_imagine to map product's image

### ISSUE THREAD

**Issue by maxmishyn** [webgriffe/SyliusActiveCampaignPlugin#83]
Currently EcommerceOrderProductMapper in getImageUrlFromPathAndChannel() method returns almost hardcoded path to the mages, what neither work with remote storages nor with non-standard (media/image/...) local paths.

I propose to use liip_imgine's CacheManager's getBrowserPath(...) method to generate the URLs. Would be good to add preferred filter name to the mapping configs in this case too. As a result, this will generate valid image URLs and it will give control over dimensions of AC synced images.

I'm adding this to the project I'm working now. Is it something what needs PR?

**Comment by lruozzi9** [comment]
Hi @maxmishyn. Feel free to suggest these changes on a PR, we will be glad to review and merge them! Any improvements will be at least considered! 😄
